name: Test_number_1
env:
  List: 'My test ssha -${{ github.sha}}'
on:
  push:
    branches: 
      - main
      
jobs:
  task_1:
    runs-on: ubuntu-latest
    
    steps:
      - name: Script_1
        run : |
            echo Hello, world!
            echo '${{ env.List}}'


  task_2:
    runs-on: ubuntu-latest
    needs: [task_1]
    
    steps:
      - name: Script_2
        run : echo My name, Git
        
      - name : Git clone
        uses  : actions/checkout@v1
        
      - name : list all my github
        run  : ls -la
     
      - name : Packages che—Åk 
        run  : |
             aws --version  
             zip
        


