name: Test_number_1
env:
  List_global: 'My test ssha -${{ github.sha }}'
on:
  push:
    branches: 
      - main
      
jobs:
  task_1:
    runs-on: ubuntu-latest
    
    steps:
      - name: Script_1
        run : |
            echo Hello, world!
            echo '${{ env.List }}'


  task_2:
    runs-on: ubuntu-latest
    needs  : [task_1]
    env    :
        list_local : 'list_local_for_task_2'
    
    
    steps:
      - name: Print list_local_for_task_2_and_steeps
        run : |
               echo '${{ env.list_local }}'
               echo 'l = ${{ env.list_local_steps }}'
        env :
            list_local_steps : 'list-local_for_steps'   
            
        
      - name : Git clone
        uses : actions/checkout@v1
       
        
      - name : list all my github
        run  : ls -la
     
      - name : Packages che—Åk 
        run  : |
             aws --version  
             zip --version
        


